data_warehouse:
  outputs:
    dev:
      dbname: data_warehouse
      host: localhost
      pass: "970211"
      port: 5432
      schema: dbt_dev
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: data_warehouse
      host: localhost
      pass: "970211"
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
